name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      
      - run: npm install
      - run: npm run prisma:generate --workspace=Backend
      - run: npm run lint --workspace=Backend
      - run: npm run test --workspace=Backend

  frontend-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      
      - run: npm install
      - run: npm run lint --workspace=Frontend
      - run: npm run build --workspace=Frontend
